version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automerge
  allow:
  - dependency-name: "@ecomplus/storefront-framework"
  - dependency-name: "@ecomplus/storefront-template"
  ignore:
  - dependency-name: "@ecomplus/storefront-framework"
    versions:
    - 5.16.10
    - 5.16.13
    - 5.16.15
    - 5.16.8
    - 5.16.9
  commit-message:
    prefix: "[skip ci] chore"
    include: scope
