name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'leomp12' || github.actor == 'dependabot-preview[bot]'

    steps:
      - name: Auto merge pull request
        uses: leomp12/automerge-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: "Auto merge #{pullRequest.number}"
